name: Uda'CityShop [latest tag] - Package with Docker

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  Push_Images_to_Docker_Hub:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Frontend to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: src/frontend/Dockerfile
          context: src/frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

      - name: Build and Push Product Catalog Service to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: src/productcatalogservice/Dockerfile
          context: src/productcatalogservice
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/productcatalogservice:latest

      - name: Build and Push Currency Service to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: src/currencyservice/Dockerfile
          context: src/currencyservice
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/currencyservice:latest

      - name: Build and Push Ad Service to DockerHub
        uses: docker/build-push-action@v2
        with:
          file: src/adservice/Dockerfile
          context: src/adservice
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/adservice:latest